### ISSUE TITLE
"Other" option fails on ingest for Degree Field

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1076]
Creating a new Honors College Thesis failed when selecting "Other" degree.

` "degree_field"=>"Other", "degree_field_other"=>"Liberal Studies",`

```
I, [2017-12-04T10:01:16.772467 #33257]  INFO -- : [d742b981-b0c4-4179-ab2a-d8cd58357c74] Completed 500 Internal Server Error in 4696ms (ActiveRecord: 38.0ms)
F, [2017-12-04T10:01:16.773628 #33257] FATAL -- : [d742b981-b0c4-4179-ab2a-d8cd58357c74]
F, [2017-12-04T10:01:16.773722 #33257] FATAL -- : [d742b981-b0c4-4179-ab2a-d8cd58357c74] ActiveModel::UnknownAttributeError (unknown attribute 'password' for User.):
F, [2017-12-04T10:01:16.773774 #33257] FATAL -- : [d742b981-b0c4-4179-ab2a-d8cd58357c74]
F, [2017-12-04T10:01:16.773831 #33257] FATAL -- : [d742b981-b0c4-4179-ab2a-d8cd58357c74] app/actors/scholars_archive/actors/add_other_field_option_actor.rb:204:in `notify_admin'
[d742b981-b0c4-4179-ab2a-d8cd58357c74] app/actors/scholars_archive/actors/add_other_field_option_actor.rb:128:in `save_custom_option'
[d742b981-b0c4-4179-ab2a-d8cd58357c74] app/actors/scholars_archive/actors/add_other_field_option_actor.rb:11:in `create'
[d742b981-b0c4-4179-ab2a-d8cd58357c74] app/actors/scholars_archive/actors/nested_fields_operations_actor.rb:11:in `create'
[d742b981-b0c4-4179-ab2a-d8cd58357c74] app/controllers/concerns/scholars_archive/works_controller_behavior.rb:26:in `create'
```

**Comment by luisgreg99** [comment]
It looks like the `config.audit_user_key = 'admin'` was missing in `config/initializers/hyrax.rb`. The notification messenger requires the admin user to be initialized.
