### ISSUE TITLE
ordered metadata error

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1655]
### Descriptive summary

Staging is experiencing HTTP 500's with the latest ordered metadata code.

```
I, [2018-09-07T08:56:44.063358 #2549]  INFO -- : [fc1044c5-3a14-4916-93df-362bb4aff83e] Completed 500 Internal Server Error in 107ms (ActiveRecord: 6.5ms)
F, [2018-09-07T08:56:44.065276 #2549] FATAL -- : [fc1044c5-3a14-4916-93df-362bb4aff83e]
F, [2018-09-07T08:56:44.065365 #2549] FATAL -- : [fc1044c5-3a14-4916-93df-362bb4aff83e] NoMethodError (undefined method `abstract' for #<String:0x000055ca846c9e00>):
F, [2018-09-07T08:56:44.065385 #2549] FATAL -- : [fc1044c5-3a14-4916-93df-362bb4aff83e]
F, [2018-09-07T08:56:44.065406 #2549] FATAL -- : [fc1044c5-3a14-4916-93df-362bb4aff83e] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:102:in `block in validate_abstracts'
[fc1044c5-3a14-4916-93df-362bb4aff83e] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:102:in `select'
[fc1044c5-3a14-4916-93df-362bb4aff83e] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:102:in `validate_abstracts'
[fc1044c5-3a14-4916-93df-362bb4aff83e] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:70:in `sort_abstracts_by_index'
[fc1044c5-3a14-4916-93df-362bb4aff83e] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:43:in `ordered_abstracts'
[fc1044c5-3a14-4916-93df-362bb4aff83e] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:16:in `abstract'
[fc1044c5-3a14-4916-93df-362bb4aff83e] app/forms/scholars_archive/nested_behavior.rb:24:in `initialize_fields'
[fc1044c5-3a14-4916-93df-362bb4aff83e] app/controllers/concerns/scholars_archive/works_controller_behavior.rb:16:in `edit'
```

**Comment by revgum** [comment]
fixed by #1656
