### ISSUE TITLE
Editing a work on staging produces an error related to metadata ordering

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1661]
### Descriptive summary

```
F, [2018-09-07T15:16:58.786974 #20008] FATAL -- : [3554fef7-d0cc-4352-afa2-47abe4785fc8] ArgumentError (comparison of Integer with String failed):
F, [2018-09-07T15:16:58.787001 #20008] FATAL -- : [3554fef7-d0cc-4352-afa2-47abe4785fc8]
F, [2018-09-07T15:16:58.787039 #20008] FATAL -- : [3554fef7-d0cc-4352-afa2-47abe4785fc8] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:62:in `sort_by'
[3554fef7-d0cc-4352-afa2-47abe4785fc8] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:62:in `sort_titles_by_index'
[3554fef7-d0cc-4352-afa2-47abe4785fc8] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:35:in `ordered_titles'
[3554fef7-d0cc-4352-afa2-47abe4785fc8] app/models/concerns/scholars_archive/has_nested_ordered_properties.rb:8:in `title'
```

http://ir-staging.library.oregonstate.edu/concern/articles/2v23vt57t/edit?locale=en

### Expected behavior
 
The form to properly render

**Comment by straleyb** [comment]
Fixed by #1663
