### ISSUE TITLE
Migration in-place work type mismatch failing to query

### ISSUE THREAD

**Issue by revgum** [osulp/Scholars-Archive#1702]
### Descriptive summary

Migration service can fail due to worktype mismatches

```
ActiveFedora::ActiveFedoraError: Model mismatch. Expected Article. Got: Default
/data0/hydra/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:210:in `class_to_load'
/data0/hydra/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:196:in `load_from_fedora'
/data0/hydra/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:181:in `find_one'
/data0/hydra/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:234:in `find_with_ids'
/data0/hydra/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/finder_methods.rb:52:in `find'
/data0/hydra/shared/bundle/ruby/2.5.0/gems/active-fedora-11.5.2/lib/active_fedora/querying.rb:3:in `find'
/data0/hydra/releases/20181015170659/app/controllers/concerns/scholars_archive/works_controller_behavior.rb:9:in `migrate_work_in_place'
```

**Comment by revgum** [comment]
fixed #1703
