### ISSUE TITLE
OAI-PMH endpoint is not working

### ISSUE THREAD

**Issue by CGillen** [osulp/Scholars-Archive#2231]
### Descriptive summary

OAI-PMH is not working right now. It's unknown since when it stopped working, possibly with the Hyrax 2.9 update.
Visiting `https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords` provides a `500` error and the following trace:

```
I, [2021-05-06T10:59:45.846153 #59077]  INFO -- : [3316e617-d2ee-4348-855c-b70ac2b44732] method=GET path=/catalog/oai format=html controller=CatalogController action=oai status=500 error='ActionView::MissingTemplate: Missing template catalog/oai, application/oai with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder, :haml]}. Searched in:
  * "/data0/hydra/releases/20210426171227/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/qa-5.6.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/flipflop-2.6.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/bundler/gems/hyrax-c31ea9237375/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/hydra-editor-5.0.4/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/blacklight-gallery-0.12.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/mailboxer-0.15.1/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/devise_cas_authenticatable-1.10.4/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/devise-4.7.3/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/browse-everything-1.1.2/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/hydra-role-management-1.0.3/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/blacklight_advanced_search-6.4.1/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/blacklight_range_limit-7.0.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/blacklight-6.24.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/kaminari-core-1.2.1/app/views"
' duration=172.57 view=0.00 db=54.54 params={"verb"=>"ListRecords"} time=18931374.75
F, [2021-05-06T10:59:45.987493 #59077] FATAL -- : [3316e617-d2ee-4348-855c-b70ac2b44732]
F, [2021-05-06T10:59:45.987631 #59077] FATAL -- : [3316e617-d2ee-4348-855c-b70ac2b44732] ActionView::MissingTemplate (Missing template catalog/oai, application/oai with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder, :haml]}. Searched in:
  * "/data0/hydra/releases/20210426171227/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/qa-5.6.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/flipflop-2.6.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/bundler/gems/hyrax-c31ea9237375/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/hydra-editor-5.0.4/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/blacklight-gallery-0.12.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/mailboxer-0.15.1/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/devise_cas_authenticatable-1.10.4/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/devise-4.7.3/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/browse-everything-1.1.2/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/hydra-role-management-1.0.3/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/blacklight_advanced_search-6.4.1/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/blacklight_range_limit-7.0.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/blacklight-6.24.0/app/views"
  * "/data0/hydra/shared/bundle/ruby/2.5.0/gems/kaminari-core-1.2.1/app/views"
):
F, [2021-05-06T10:59:45.987736 #59077] FATAL -- : [3316e617-d2ee-4348-855c-b70ac2b44732]
F, [2021-05-06T10:59:45.987902 #59077] FATAL -- : [3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/path_set.rb:48:in `find'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/lookup_context.rb:116:in `find'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/renderer/abstract_renderer.rb:20:in `find_template'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/renderer/template_renderer.rb:10:in `render'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/renderer/renderer.rb:44:in `render_template'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/renderer/renderer.rb:25:in `render'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/rendering.rb:103:in `_render_template'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/streaming.rb:219:in `_render_template'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/rendering.rb:84:in `render_to_body'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/abstract_controller/rendering.rb:25:in `render'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/rendering.rb:36:in `render'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
[3316e617-d2ee-4348-855c-b70ac2b44732] /data1/deploy-rails/.rbenv/versions/2.5.5/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/core_ext/benchmark.rb:14:in `ms'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[3316e617-d2ee-4348-855c-b70ac2b44732] activerecord (5.2.5) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/instrumentation.rb:45:in `render'
[3316e617-d2ee-4348-855c-b70ac2b44732] /data0/hydra/shared/bundle/ruby/2.5.0/bundler/gems/blacklight_oai_provider-4cb048bd52fe/lib/blacklight_oai_provider/catalog_controller_behavior.rb:18:in `oai'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/abstract_controller/base.rb:194:in `process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/rendering.rb:30:in `process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/callbacks.rb:132:in `run_callbacks'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/abstract_controller/callbacks.rb:41:in `process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/rescue.rb:22:in `process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/notifications.rb:168:in `block in instrument'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/notifications.rb:168:in `instrument'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] activerecord (5.2.5) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/abstract_controller/base.rb:134:in `process'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionview (5.2.5) lib/action_view/rendering.rb:32:in `process'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal.rb:191:in `dispatch'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_controller/metal.rb:252:in `dispatch'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/routing/route_set.rb:34:in `serve'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/journey/router.rb:52:in `block in serve'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/journey/router.rb:35:in `each'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/journey/router.rb:35:in `serve'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/routing/route_set.rb:840:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] devise_cas_authenticatable (1.10.4) lib/devise_cas_authenticatable/single_sign_out/rack.rb:14:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[3316e617-d2ee-4348-855c-b70ac2b44732] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[3316e617-d2ee-4348-855c-b70ac2b44732] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/head.rb:12:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/cookies.rb:670:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] active-fedora (12.1.1) lib/active_fedora/ldp_cache.rb:26:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] flipflop (2.6.0) lib/flipflop/feature_cache.rb:12:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/callbacks.rb:98:in `run_callbacks'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] honeycomb-beeline (2.3.0) lib/honeycomb/integrations/rack.rb:50:in `block in call'
[3316e617-d2ee-4348-855c-b70ac2b44732] honeycomb-beeline (2.3.0) lib/honeycomb/client.rb:70:in `start_span'
[3316e617-d2ee-4348-855c-b70ac2b44732] honeycomb-beeline (2.3.0) lib/honeycomb/integrations/rack.rb:35:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] lograge (0.11.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[3316e617-d2ee-4348-855c-b70ac2b44732] railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/tagged_logging.rb:28:in `tagged'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/tagged_logging.rb:71:in `tagged'
[3316e617-d2ee-4348-855c-b70ac2b44732] railties (5.2.5) lib/rails/rack/logger.rb:26:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] activesupport (5.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] actionpack (5.2.5) lib/action_dispatch/middleware/static.rb:127:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] railties (5.2.5) lib/rails/engine.rb:524:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] puma (3.12.6) lib/puma/configuration.rb:227:in `call'
[3316e617-d2ee-4348-855c-b70ac2b44732] puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
[3316e617-d2ee-4348-855c-b70ac2b44732] puma (3.12.6) lib/puma/server.rb:476:in `process_client'
[3316e617-d2ee-4348-855c-b70ac2b44732] puma (3.12.6) lib/puma/server.rb:334:in `block in run'
[3316e617-d2ee-4348-855c-b70ac2b44732] puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

### Expected behavior
OAI-PMH endpoint (https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords) provides a list of metadata records for harvesting.

### Actual behavior
OAI-PMH endpoint (https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords) results in `500` status code and error page

### Steps to reproduce the behavior
Visit `https://ir.library.oregonstate.edu/catalog/oai?verb=ListRecords`

**Comment by CGillen** [comment]
QA:
- [ ] Visit ir.library.oregonstate.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc - Page renders
- [ ] Use show source option from browser - XML renders
- [ ] Attempt to harvest with OregonExplorer - harvest succeeds

**Comment by CGillen** [comment]
Can't attempt a harvest on OE-test because of certificate issues but all the endpoints look like they're responding
