### ISSUE TITLE
uploading a new version errors out

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#519]
when uploading a new version of a file, the "sorry, somethign went wrong" error appears. no new file is uploaded.

**Comment by revgum** [comment]
has this error in the logs:

```F, [2017-04-11T10:25:38.021908 #7659] FATAL -- : [2a4c4bca-d430-44c6-98af-b78de3560e60] ArgumentError (wrong number of arguments (1 for 2)):
F, [2017-04-11T10:25:38.021974 #7659] FATAL -- : [2a4c4bca-d430-44c6-98af-b78de3560e60]
F, [2017-04-11T10:25:38.022065 #7659] FATAL -- : [2a4c4bca-d430-44c6-98af-b78de3560e60] /data0/hydra/shared/bundle/ruby/2.2.0/bundler/gems/hyrax-dcf004f47c09/app/actors/hyrax/actors/file_actor.rb:23:in `ingest_file'
[2a4c4bca-d430-44c6-98af-b78de3560e60] /data0/hydra/shared/bundle/ruby/2.2.0/bundler/gems/hyrax-dcf004f47c09/app/actors/hyrax/actors/file_set_actor.rb:86:in `update_content'
[2a4c4bca-d430-44c6-98af-b78de3560e60] /data0/hydra/shared/bundle/ruby/2.2.0/bundler/gems/hyrax-dcf004f47c09/app/controllers/concerns/hyrax/file_sets_controller_behavior.rb:163:in `attempt_update'
[2a4c4bca-d430-44c6-98af-b78de3560e60] /data0/hydra/shared/bundle/ruby/2.2.0/bundler/gems/hyrax-dcf004f47c09/app/controllers/concerns/hyrax/file_sets_controller_behavior.rb:65:in `update'```

**Comment by vantuyls** [comment]
this works now. magic!
